services:
  # Main Server Service
  - type: web
    name: anythingllm-server
    env: node
    plan: starter
    buildCommand: ./render-server-build.sh
    startCommand: cd server && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: SIG_KEY
        generateValue: true
      - key: SIG_SALT
        generateValue: true
      - key: VECTOR_DB
        value: lancedb
      - key: TTS_PROVIDER
        value: native
      - key: WHISPER_PROVIDER
        value: local
      - key: DATABASE_URL
        fromDatabase:
          name: anythingllm-db
          property: connectionString
      - key: LLM_PROVIDER
        value: openrouter
      - key: OPENROUTER_API_KEY
        value: REPLACE_WITH_YOUR_OPENROUTER_API_KEY
      - key: OPENROUTER_MODEL_PREF
        value: anthropic/claude-3-haiku
      - key: EMBEDDING_ENGINE
        value: native
      - key: EMBEDDING_MODEL_PREF
        value: Xenova/all-MiniLM-L6-v2
    
  # Document Collector Service
  - type: web
    name: anythingllm-collector
    env: node
    plan: starter
    buildCommand: ./render-collector-build.sh
    startCommand: cd collector && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 10000

  # PostgreSQL Database
databases:
  - name: anythingllm-db
    databaseName: anythingllm
    user: anythingllm